Repository ita-social-projects/Car-Front-End, pull requests merged in 2021-02, with the labels that each got.

#96 Closed #95 - Restructure project
  SoftServeCarMobile/src/activity/journey/Journey.tsx
  SoftServeCarMobile/src/activity/journey/JourneyTabs.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/search-journey/SearchJouneyStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/JourneyApplicant.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicantStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/AllJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/PastJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/ScheduledJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/UpcomingJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/card/TouchableCard.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/card/TouchableCardStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourney.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourneyStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/map-bar/TouchableMapBar.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/map-bar/TouchableMapBarStyle.tsx
  SoftServeCarMobile/src/activity/journey/touchable-navigation-block/TouchableNavigationBlock.tsx
  SoftServeCarMobile/src/activity/journey/touchable-navigation-block/TouchableNavigationBlockStyle.tsx
  SoftServeCarMobile/src/activity/messages/Messages.tsx
  SoftServeCarMobile/src/activity/my-profile/MyProfile.tsx
  SoftServeCarMobile/src/activity/my-profile/MyProfileTabs.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/avatar-logo/AvatarLogoTitle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/avatar-logo/AvatarLogoTitleStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/touchable-navigation-card/TouchableNavigationCard.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/touchable-navigation-card/TouchableNavigationCardStyle.tsx
  SoftServeCarMobile/src/activity/notifications/Notifications.tsx
  SoftServeCarMobile/src/components/BottomPopup/menu-button/MenuButton.tsx
  SoftServeCarMobile/src/components/Cars/Cars.tsx
  SoftServeCarMobile/src/components/navigation/AppTabs.tsx
Labels: task

#100 Closed #8 - Applicant profile
  SoftServeCarMobile/android/app/src/main/assets/.DS_Store
  SoftServeCarMobile/api-service/user-service/UserService.tsx
  SoftServeCarMobile/ios/SoftServeCarMobile.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  SoftServeCarMobile/src/activity/journey/JourneyTabs.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/create-journey/CreateJourney.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicantStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPageStyle.tsx
  SoftServeCarMobile/src/components/navigation/AppTabs.tsx
Labels: story

#106 Closed #105 - Fix fonts IOS
  SoftServeCarMobile/android/app/src/main/java/com/softservecarmobile/MainApplication.java
  SoftServeCarMobile/android/settings.gradle
  SoftServeCarMobile/font-manager.tsx
  SoftServeCarMobile/ios/Podfile
  SoftServeCarMobile/ios/SoftServeCarMobile.xcodeproj/project.pbxproj
  SoftServeCarMobile/ios/SoftServeCarMobile.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  SoftServeCarMobile/ios/SoftServeCarMobile/Info.plist
  SoftServeCarMobile/package-lock.json
  SoftServeCarMobile/package.json
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicantStyle.tsx
  SoftServeCarMobile/src/components/journey-new-applicant/JourneyNewApplicant.tsx
  SoftServeCarMobile/src/components/journey-new-applicant/JourneyNewApplicantStyle.tsx
  SoftServeCarMobile/yarn.lock
Labels: bug, pri:critical

#108 Closed #107 - Remove comments
  SoftServeCarMobile/babel.config.js
  SoftServeCarMobile/environment.tsx
  SoftServeCarMobile/index.js
  SoftServeCarMobile/react-native.config.js
  SoftServeCarMobile/src/components/journey-new-applicant/JourneyNewApplicantStyle.tsx
  SoftServeCarMobile/tsconfig.json
Labels: bug, pri:low

#117 Closed #116 - Refactor fonts manager
  .github/workflows/CI.yml
  .idea/Car-Front-End.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .vs/FrontEnd/v16/.suo
  .vs/FrontEnd/v16/Browse.VC.db
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  SoftServeCarMobile/.gitignore
  SoftServeCarMobile/Environment.tsx
  SoftServeCarMobile/__tests__/ChatService-test.tsx
  SoftServeCarMobile/__tests__/LoginService-test.tsx
  SoftServeCarMobile/__tests__/PreferencesService-test.tsx
  SoftServeCarMobile/__tests__/UserService-test.tsx
  SoftServeCarMobile/api-service/APIService.tsx
  SoftServeCarMobile/api-service/car-service/CarService.tsx
  SoftServeCarMobile/assets/images/journey/bermuda-delivery-car-service.png
  SoftServeCarMobile/font-manager.tsx
  SoftServeCarMobile/ios/SoftServeCarMobile.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  SoftServeCarMobile/src/activity/chat/Chat.tsx
  SoftServeCarMobile/src/activity/journey/Journey.tsx
  SoftServeCarMobile/src/activity/journey/JourneyStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicantStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPageStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/all-journeys/AllJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/all-journeys/AllJourneysStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/past-journeys/PastJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/past-journeys/PastJourneysStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/scheduled-journeys/ScheduledJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/scheduled-journeys/ShceduledJourneysStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/upcoming-journeys/UpcomingJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/upcoming-journeys/UpcomingJourneysStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourney.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourneyStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-tabs/JourneyTabsStyle.tsx
  SoftServeCarMobile/src/activity/journey/touchable-navigation-block/TouchableNavigationBlockStyle.tsx
  SoftServeCarMobile/src/activity/login/LoginStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/avatar-logo/AvatarLogoTitleStyle.tsx
  SoftServeCarMobile/src/components/fonts/Font.tsx
  SoftServeCarMobile/src/components/fonts/Fonts.android.tsx
  SoftServeCarMobile/src/components/fonts/Fonts.ios.tsx
  SoftServeCarMobile/src/components/journey-new-applicant/JourneyNewApplicant.tsx
  SoftServeCarMobile/src/components/journey-new-applicant/JourneyNewApplicantStyle.tsx
  SoftServeCarMobile/src/components/navigation/app-tabs/AppTabsStyle.tsx
Labels: pri:low, task

#120 Closed ita-social-projects/Car-Back-End#13 - [Search for Journey] Search Result
  SoftServeCarMobile/api-service/car-service/CarService.tsx
  SoftServeCarMobile/assets/images/journey/bad-seacrh-result.png
  SoftServeCarMobile/src/activity/journey/journey-activity/search-journey/SearchJouneyStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/scheduled-journeys/ScheduledJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/upcoming-journeys/UpcomingJourneys.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/search-results/bad-search-result/BadSearchResult.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/search-results/bad-search-result/BadSearchResultStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/search-results/ok-search-result/OkSearchResult.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/search-results/ok-search-result/OkSearchResultStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourney.tsx
  SoftServeCarMobile/src/activity/journey/journey-tabs/JourneyTabs.tsx
  SoftServeCarMobile/src/activity/journey/journey-tabs/JourneyTabsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/MyProfileTabs.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/Cars.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/CarsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCarsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabs.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/car-tabs/CarTabsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/edit-cars/EditCars.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/edit-cars/EditCarsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/touchable-navigation-card/TouchableNavigationCard.tsx
  SoftServeCarMobile/src/components/cars/Cars.tsx
Labels: story

#127 HotFix Modal conflict + New Applicant page temporary location
  SoftServeCarMobile/Environment.tsx
  SoftServeCarMobile/package-lock.json
  SoftServeCarMobile/package.json
  SoftServeCarMobile/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  SoftServeCarMobile/src/activity/notifications/NotificationComponent.tsx
  SoftServeCarMobile/src/components/car-text-input/CarTextInput.tsx
Labels: bug, subtask

#135 Closed #134 - Fix My Profile header (IOS)
  SoftServeCarMobile/.DS_Store
  SoftServeCarMobile/ios/SoftServeCarMobile.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  SoftServeCarMobile/src/activity/journey/journey-activity/create-journey/CreateJourneyStyle.tsx
  SoftServeCarMobile/src/activity/journey/journey-activity/search-journey/SearchJouneyStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/address-book/AddressBookStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/details/DetailsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/PreferencesStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/settings/SettingsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-tabs/MyProfileTabsStyle.tsx
Labels: bug, pri:high

#142 Closed #141 - Change all Button components to TouchableOpacity
  SoftServeCarMobile/src/activity/login/Login.tsx
  SoftServeCarMobile/src/activity/login/LoginStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/details/Details.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/details/DetailsStyle.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/ChooseOptionComponent.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx
  SoftServeCarMobile/src/activity/my-profile/my-profile-activity/preferences/PreferencesStyle.tsx
Labels: task

#160 Update CI.yml
  .github/workflows/CI.yml
Labels: subtask

#163 Revert "Node modules ignore"
  .gitignore
  .idea/Car-Front-End.iml
  .idea/modules.xml
  SoftServeCarMobile/.gitignore
Labels: pri:critical

#167 Closed #164 - Create & Implement Journey Card component
  Car/android/app/build.gradle
  Car/android/app/src/debug/java/com/car/ReactNativeFlipper.java
  Car/android/app/src/main/AndroidManifest.xml
  Car/android/app/src/main/java/com/car/MainActivity.java
  Car/android/app/src/main/java/com/car/MainApplication.java
  Car/ios/Car.xcodeproj/project.pbxproj
  Car/ios/Car.xcodeproj/xcshareddata/xcschemes/Car.xcscheme
  Car/ios/Car.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  Car/ios/assets/app.json
  Car/ios/assets/assets/images/default-user-photo.jpg
  Car/ios/assets/assets/images/journey/bad-seacrh-result.png
  Car/ios/assets/assets/images/journey/bermuda-delivery-car-service.png
  Car/ios/assets/assets/images/journey/bermuda-searching.png
  Car/ios/assets/node_modules/.package-lock.json
  Car/ios/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon-mask.png
  Car/ios/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon.png
  Car/ios/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@2x.png
  Car/ios/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.png
  Car/ios/assets/node_modules/react-native-ratings/src/images/airbnb-star-selected.png
  Car/ios/assets/node_modules/react-native-ratings/src/images/airbnb-star.png
  Car/ios/assets/node_modules/react-native-ratings/src/images/bell.png
  Car/ios/assets/node_modules/react-native-ratings/src/images/heart.png
  Car/ios/assets/node_modules/react-native-ratings/src/images/rocket.png
  Car/ios/assets/node_modules/react-native-ratings/src/images/star.png
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/AntDesign.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Entypo.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/EvilIcons.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Feather.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/FontAwesome.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/FontAwesome5Free.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/FontAwesome5Free_meta.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Fontisto.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Foundation.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Ionicons.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/MaterialIcons.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Octicons.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/SimpleLineIcons.json
  Car/ios/assets/node_modules/react-native-vector-icons/glyphmaps/Zocial.json
  Car/ios/assets/package.json
  Car/ios/main.jsbundle
  Car/package-lock.json
  Car/package.json
  Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/search-results/ok-search-result/OkSearchResult.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/search-results/ok-search-result/OkSearchResultStyle.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo-title/AvatarLogoTitle.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo-title/AvatarLogoTitleStyle.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo/AvatarLogoTitle.tsx
  Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
  Car/src/activity/my-profile/my-profile-tabs/MyProfileTabs.tsx
  Car/src/components/avatar-logo/AvatarLogo.tsx
  Car/src/components/avatar-logo/AvatarLogoStyle.tsx
  Car/src/components/journey-card/JourneyCard.tsx
  Car/src/components/journey-card/JourneyCardStyle.tsx
  Car/yarn.lock
  azure-pipelines.yml
Labels: task

#179 Closed #217 - All, past, upcoming menu on the journey page
  Car/api-service/journey-service/JourneyService.tsx
  Car/assets/images/journey/bermuda-searching.png
  Car/src/activity/journey/Journey.tsx
  Car/src/activity/journey/JourneyStyle.tsx
  Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/all-journeys/AllJourneys.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/past-journeys/PastJourneys.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/past-journeys/PastJourneysStyle.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/scheduled-journeys/ScheduledJourneys.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/scheduled-journeys/ShceduledJourneysStyle.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/upcoming-journeys/UpcomingJourneys.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/tabs/upcoming-journeys/UpcomingJourneysStyle.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/touchable/journey/TouchableJourneyStyle.tsx
  Car/src/components/journey-card/JourneyCard.tsx
  Car/src/components/journey-card/JourneyCardStyle.tsx
Labels: task

#180 Closed #143 - Refactored models
  Car/api-service/car-service/CarService.tsx
  Car/api-service/journey-service/JourneyService.tsx
  Car/dto/CarDto.tsx
  Car/ios/Car/Images.xcassets/AppIcon.appiconset/Contents.json
  Car/ios/Car/Images.xcassets/Contents.json
  Car/ios/Images.xcassets/AppIcon.appiconset/Contents.json
  Car/ios/Images.xcassets/Contents.json
  Car/models/Address.tsx
  Car/models/Brand.tsx
  Car/models/Car.tsx
  Car/models/CarDTO.tsx
  Car/models/CarInfoDTO.tsx
  Car/models/Chat.tsx
  Car/models/Journey.tsx
  Car/models/Location.tsx
  Car/models/LocationType.tsx
  Car/models/Message.tsx
  Car/models/Model.tsx
  Car/models/Notification.tsx
  Car/models/Schedule.tsx
  Car/models/Stop.tsx
  Car/models/User.tsx
  Car/models/UserPreferences.tsx
  Car/models/UserWithAvatarDTO.tsx
  Car/package-lock.json
  Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/Cars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx
  Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx
  Car/src/components/activity-indicator/Indicator.tsx
  Car/src/components/activity-indicator/IndicatorStyle.tsx
  Car/src/components/journey-card/JourneyCard.tsx
  Car/src/components/journey-card/JourneyCardStyle.tsx
Labels: bug, task

#187 Closed #186 - Fix Journey Segment Control Style
  Car/src/activity/journey/JourneyStyle.tsx
Labels: bug

#196 Closed #192 - Add Session (30 days)
  Car/android/.project
  Car/android/.settings/org.eclipse.buildship.core.prefs
  Car/android/app/.classpath
  Car/android/app/.project
  Car/android/app/.settings/org.eclipse.buildship.core.prefs
  Car/ios/Podfile
  Car/src/activity/auth/AuthProvider.tsx
  Car/src/activity/journey/journey-activity/create-journey/SearchResultProps.ts
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicantStyle.tsx
  Car/src/activity/notifications/Notifications.tsx
  Car/src/common/interfaces/NotificationProps.tsx
  Car/src/components/journey-new-applicant/JourneyNewApplicant.tsx
  Car/src/components/navigation/Providers.tsx
  Car/src/components/navigation/Routes.tsx
  Car/src/components/navigation/app-tabs/AppTabs.tsx
  Car/src/components/new-notification/NewNotification.tsx
  Car/src/components/user-avatar/UserAvatar.tsx
  Car/src/components/user-avatar/UserAvatarStyle.tsx
Labels: task

#199 Closed #198 - Fix session
  Car/ios/Car.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  Car/src/components/navigation/Routes.tsx
Labels: bug

#207 Closed #200 - Add cars fixed
  Car/Environment.tsx
  Car/api-service/brand-service/BrandService.tsx
  Car/api-service/car-service/CarService.tsx
  Car/api-service/model-service/ModelService.tsx
  Car/dto/CarDto.tsx
  Car/models/Brand.tsx
  Car/models/Car.tsx
  Car/models/Journey.tsx
  Car/models/Model.tsx
  Car/models/car/CarBrand.tsx
  Car/models/car/CarColor.tsx
  Car/models/car/CarModel.tsx
  Car/models/car/CarViewModel.tsx
  Car/models/car/CreateCarViewModel.tsx
  Car/models/car/UpdateCarViewModel.tsx
  Car/package-lock.json
  Car/src/activity/my-profile/my-profile-activity/cars/Cars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCarsStyle.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/edit-cars/EditCars.tsx
  Car/src/components/car-drop-down-picker/CarDropDownPicker.tsx
  Car/src/components/navigation/Routes.tsx
  Car/src/components/navigation/app-tabs/AppTabs.tsx
Labels: bug

#205 Closed #204 - Create functionality to change/upload avatar
  Car/android/app/src/main/AndroidManifest.xml
  Car/api-service/car-service/CarService.tsx
  Car/api-service/user-service/UserService.tsx
  Car/ios/Car.xcworkspace/xcuserdata/reverend.xcuserdatad/UserInterfaceState.xcuserstate
  Car/ios/Car/Info.plist
  Car/ios/Podfile.lock
  Car/ios/Pods/Local Podspecs/react-native-orientation.podspec.json
  Car/ios/Pods/Manifest.lock
  Car/package-lock.json
  Car/package.json
  Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo-title/AvatarLogoTitle.tsx
  Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
  Car/src/activity/my-profile/my-profile-activity/settings/SettingsStyle.tsx
  Car/src/components/avatar-logo/AvatarLogo.tsx
  Car/src/components/journey-card/JourneyCard.tsx
  Car/yarn.lock
Labels: bug, subtask, task

#210 Closed #209 - Change api url to primary server
  Car/Environment.tsx
  Car/android/app/src/main/java/com/car/MainApplication.java
  Car/android/settings.gradle
  Car/ios/Podfile
  Car/package-lock.json
  Car/package.json
  Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo-title/AvatarLogoTitle.tsx
  Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
  Car/src/activity/my-profile/my-profile-tabs/MyProfileTabs.tsx
  Car/src/activity/notifications/notifications-tabs/NotificationsTabsStyle.tsx
  Car/src/components/styles/HeaderStyle.tsx
  Car/yarn.lock
Labels: task

#219 Closed #218 - Add loading indicators
  Car/src/activity/my-profile/my-profile-activity/cars/Cars.tsx
  Car/src/activity/my-profile/my-profile-activity/details/Details.tsx
  Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx
  Car/src/activity/my-profile/my-profile-activity/preferences/PreferencesStyle.tsx
Labels: task

#232 Closed #231 - Replace exception page with alert window
  Car/__tests__/App-test.js
  Car/api-service/Interceptor.tsx
  Car/api-service/car-service/CarService.tsx
  Car/api-service/journey-service/JourneyService.tsx
  Car/api-service/notifications-service/NotificationsService.tsx
  Car/api-service/user-service/UserService.tsx
  Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/search-results/bad-search-result/BadSearchResult.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/tabs/past-journeys/PastJourneys.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/tabs/scheduled-journeys/ScheduledJourneys.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/tabs/upcoming-journeys/UpcomingJourneys.tsx
  Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
  Car/src/activity/messages/chat/simple-message/SimpleMessage.tsx
  Car/src/activity/messages/messages-tabs/MessagesTabs.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo-title/AvatarLogoTitle.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/Cars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/edit-cars/EditCars.tsx
  Car/src/activity/my-profile/my-profile-activity/details/Details.tsx
  Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx
  Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
  Car/src/activity/notifications/Notifications.tsx
  Car/src/components/auth/AuthProvider.tsx
  Car/src/components/avatar-logo/AvatarLogo.tsx
  Car/src/components/exception/Exception.tsx
  Car/src/components/exception/ExceptionStyle.tsx
  Car/src/components/journey-card/JourneyCard.tsx
  Car/src/components/journey-new-applicant/JourneyNewApplicant.tsx
  Car/src/components/navigation/Navigation.tsx
  Car/src/components/navigation/Routes.tsx
Labels: task

#234 Closes #245 - Journey page (list of journeys), combinated useeffects
  Car/src/activity/journey/JourneyStartPage.tsx
Labels: task

#238 Closed #236 - Remove multiple alert windows
  Car/android/settings.gradle
  Car/api-service/Interceptor.tsx
  Car/ios/Podfile
  Car/src/activity/journey/JourneyStartPage.tsx
  Car/src/activity/journey/JourneyStartPageStyle.tsx
  Car/src/activity/journey/journey-activity/search-journey/SearchJourney.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-applicant/JourneyApplicant.tsx
  Car/src/activity/journey/journey-activity/segment-control-activities/journey-page/JourneyPage.tsx
  Car/src/activity/journey/journey-tabs/JourneyTabs.tsx
  Car/src/activity/messages/chat/simple-message/SimpleMessage.tsx
  Car/src/activity/messages/messages-tabs/MessagesTabs.tsx
  Car/src/activity/my-profile/my-profile-activity/avatar-logo-title/AvatarLogoTitle.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/Cars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/add-cars/AddCars.tsx
  Car/src/activity/my-profile/my-profile-activity/cars/edit-cars/EditCars.tsx
  Car/src/activity/my-profile/my-profile-activity/details/Details.tsx
  Car/src/activity/my-profile/my-profile-activity/preferences/Preferences.tsx
  Car/src/activity/my-profile/my-profile-activity/settings/Settings.tsx
  Car/src/activity/notifications/Notifications.tsx
  Car/src/components/avatar-logo/AvatarLogo.tsx
  Car/src/components/error-alert/ErrorAlert.tsx
  Car/src/components/navigation/Routes.tsx
Labels: task

#251 Closed #250 - Customize error alert
  Car/api-service/Axios.tsx
  Car/assets/images/surprised-car.png
  Car/package-lock.json
  Car/package.json
  Car/src/activity/messages/chat/Chat.tsx
  Car/src/activity/my-profile/my-profile-activity/address-book/AddressBook.tsx
  Car/src/activity/notifications/Notifications.tsx
  Car/src/activity/notifications/notifications-tabs/NotificationsTabs.tsx
  Car/src/common/enums/AccentColors.ts
  Car/src/components/auth/AuthContext.tsx
  Car/src/components/avatar-logo/AvatarLogo.tsx
  Car/src/components/error-alert/ErrorAlert.tsx
  Car/src/components/error-alert/ErrorAlertStyle.tsx
  Car/src/components/journey-new-applicant/JourneyNewApplicant.tsx
  Car/src/components/navigation/Routes.tsx
  Car/src/components/navigation/app-tabs/AppTabs.tsx
  Car/src/components/navigation/app-tabs/AppTabsList.tsx
  Car/src/components/new-notification/NewNotification.tsx
  Car/src/components/styles/IconStyle.ts
  Car/src/components/user-avatar/UserAvatar.tsx
  Car/src/components/user-avatar/UserAvatarStyle.ts
  Car/yarn.lock
Labels: task
